//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Diagnostics;
using System.Windows.Forms;

namespace SQLComparator
{
    namespace My
    {

        //NOTE: This file is auto-generated; do not modify it directly.  To make changes,
        // or if you encounter build errors in this file, go to the Project Designer
        // (go to Project Properties or double-click the My Project node in
        // Solution Explorer), and make changes on the Application tab.
        //
        internal partial class MyApplication : Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase
        {

            [global::System.Diagnostics.DebuggerStepThroughAttribute()]
            public MyApplication()
                : base(Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            {
                this.IsSingleInstance = true;
                this.EnableVisualStyles = true;
                this.SaveMySettingsOnExit = true;
                this.ShutdownStyle = Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses;
                this.StartupNextInstance += new Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventHandler(MyApplication_StartupNextInstance);

            }

            [global::System.Diagnostics.DebuggerStepThroughAttribute()]
            protected override void OnCreateMainForm()
            {
                this.MainForm = new global::SQLComparator.Main();
                MyApplication._MainForm = (SQLComparator.Main) this.MainForm;
                if (_Args != null)
                    this.MainForm.Tag = _Args;
            }

            private void MyApplication_StartupNextInstance(object sender, Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs e)
            {
                if (e.CommandLine.Count== 1)
                    MyApplication._MainForm.LoadSettings(e.CommandLine[0]);
            }

            private static MyApplication MyApp;
            internal static MyApplication Application
            {
                get
                {
                    return MyApp;
                }
            }

            [STAThread]
            static void Main(string[] args)
            {
                MyApp = new MyApplication();
                My.MyApplication._Args = args;
                MyApp.Run(args);

            }

        }
    }

} //end of root namespace